services:
  orthanc-backend:
    image: $DOCKER_IMAGE_ORTHANC
    command: /run/secrets/    # Path to the configuration files (stored as secrets)
    env_file:
      - /home/ec2-user/.orthanc.env
    secrets:
      - orthanc.json
      - site.pem
    restart: always
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1'
          memory: 1536M
    networks:
      - orthnet
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      disable: true  # Healthcheck is driven by Envoy, see envoy.yaml for healthcheck configuration
    profiles:
      - nginx-proxy 
      - envoy-proxy
  nginx-proxy:
    image: $DOCKER_IMAGE_NGINX
    container_name: nginx
    ports:
      - 443:443
      - 11112:11112
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 512M
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./$SITE_KEY_CERT_FILE:/etc/nginx/conf.d/site.pem
    networks:
      - orthnet
    profiles:
      - nginx-proxy
  envoy-proxy:
    image: $DOCKER_IMAGE_ENVOY 
    container_name: envoy
    ports:
      - 9901:9901
      - 443:443
      - 11112:11112
    command:
      - "-c"
      - "/etc/envoy/envoy.yaml"
      - "--log-level"
      - "info"
      - "--component-log-level"
      - "upstream:info,http:debug"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 512M
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./$SITE_KEY_CERT_FILE:/etc/ssl/certs/site.pem
      - /home/envoy:/home/envoy
    networks:
      - orthnet
    profiles:
      - envoy-proxy
secrets:
  orthanc.json:
    file: $ORTHANC_CONFIG_FILE
  site.pem:
    file: $SITE_KEY_CERT_FILE
networks:
  orthnet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'false'